### ISSUE TITLE
验证失败后不会清空session验证码的值,这似乎有点问题

### ISSUE THREAD

**Issue by lq10601** [top-think/think-captcha#36]
如果没有别的防御,就单看这个验证,验证失败后没有清空session,那就可以暴力破解直到正确的为止,是不是这样?
我在最后返回之前加了清除`Session::delete($key, '');`

**Comment by liu21st** [comment]
失败后是否清空session是有配置的 不是强制，而且默认配置就是true

**Comment by lq10601** [comment]
> 失败后是否清空session是有配置的 不是强制，而且默认配置就是true

那不是验证成功后的操作吗?

**Comment by liu21st** [comment]
抱歉看错了，一般使用Validate类的token规则验证的话 失败会自动重置

**Comment by liu21st** [comment]
Captcha类里面不强制是因为可能存在多次调用的情况
