### ISSUE TITLE
无法通过composer下载

### ISSUE THREAD

**Issue by ccpwcn** [top-think/think-captcha#38]
composer配置没问题，安装其他包可以，但是安装think-captcha有可能会提示错误，如下：
![微信截图_20190421171809](https://user-images.githubusercontent.com/5465756/56468047-80f64180-6459-11e9-8c0e-5274d03732e9.png)
不是百分百必现的，碰到过几次。

**Comment by ritaswc** [comment]
请使用composer官方服务器下载，加速服务器是会有这样的问题的
