### ISSUE TITLE
这个是否可以不自动加载

### ISSUE THREAD

**Issue by sir-volcano** [top-think/think-captcha#51]
![img](https://user-images.githubusercontent.com/23112914/71808797-a7244600-30a9-11ea-9434-5789fe1230dc.png)

[路由的节点应该让我们自己掌控。而不是由官方来帮我们注册把])

**Comment by sir-volcano** [comment]
![image](https://user-images.githubusercontent.com/23112914/71808748-907def00-30a9-11ea-827d-2a040b04cacd.png)

**Comment by sir-volcano** [comment]
class CaptchaService extends Service
{
    public function boot(Route $route)
    {
        $route->get('captcha/[:config]', "\\think\\captcha\\CaptchaController@index");

        Validate::maker(function ($validate) {
            $validate->extend('captcha', function ($value) {
                return captcha_check($value);
            }, ':attribute错误!');
        });
    }
}
就是这个类文件

**Comment by liu21st** [comment]
你可以重新注册就覆盖默认的路由了
