### ISSUE TITLE
该库好像与 think-swoole 不兼容

### ISSUE THREAD

**Issue by xaboy** [top-think/think-captcha#53]
安装该库后会导致启动swoole服务后第一次打开页面没有加载路由而导致报错,刷新一下就正常打开了
删除该库后就正常了

**Comment by huan-xi** [comment]
很容易出校404

**Comment by xaboy** [comment]
我换了个验证码类就好了

**Comment by huan-xi** [comment]
有推荐的吗

**Comment by xaboy** [comment]
我用的 [gregwar/captcha](https://github.com/Gregwar/Captcha)

**Comment by huan-xi** [comment]
好的，感谢
