### ISSUE TITLE
我是来投诉的^_^

### ISSUE THREAD

**Issue by erzh** [top-think/think-captcha#6]
亲，你的验证码类参考我很多年前写的这个代码，http://www.iteye.com/topic/469170。
参考成分太大了，至少也该有个参考备注吧。

另外我写的未正式发布框架（https://github.com/windwork）欢迎来访。

**Comment by yunwuxin** [comment]
这个。。。  :smiley: 
我是用原来的3.2的改的
https://github.com/top-think/thinkphp-extend/blob/master/extend/org/Verify.php

**Comment by erzh** [comment]
老早的tp版本就参考这个了啊，只是这个代码中的版权声明不地道啊

**Comment by ganlvtech** [comment]
`
    /**  
     *      正弦型函数解析式：y=Asin(ωx+φ)+b 
     *      各常数值对函数图像的影响： 
     *        φ：决定波形与X轴位置关系或横向移动距离（左加右减） 
     */  
    protected static function _writeCurve() {  
// ......
        $f = mt_rand(-self::$imageH/4, self::$imageH/4);   // X轴方向偏移量  
// ......
                $py = $A * sin($w*$px + $f)+ $b + self::$imageH/2;  // y = Asin(ωx+φ) + b  
// ......
`

横向移动距离应该是`y=Asin(ω(x-x0))+b`

单纯写φ应该是(-pi,pi]，而不是[-height/4,height/4)之间的整数，又因为1 rad = 57.3°，这将导致φ几乎全是60°的整数倍。
然而结果是符合预期的，但是原理上不太对。
